INSERT INTO products (product_name,department_name,price,stock_quantity) values ("TV","Electronics",500,10);
INSERT INTO products (product_name,department_name,price,stock_quantity) values ("Playstation","Electronics",300,15);
INSERT INTO products (product_name,department_name,price,stock_quantity) values ("Couch","Furnitures",700,5);
INSERT INTO products (product_name,department_name,price,stock_quantity) values ("Griddler","Appliances",500,10);
INSERT INTO products (product_name,department_name,price,stock_quantity) values ("Soccer Ball","Sports",30,50);
INSERT INTO products (product_name,department_name,price,stock_quantity) values ("Manchester United Jersey","Sports",60,100);
INSERT INTO products (product_name,department_name,price,stock_quantity) values ("Dining Table","Furnitures",1000,5);
INSERT INTO products (product_name,department_name,price,stock_quantity) values ("Dog Food","Pet Supplies",100,10);
INSERT INTO products (product_name,department_name,price,stock_quantity) values ("Balexa","Smart Home",20,5000);
INSERT INTO products (product_name,department_name,price,stock_quantity) values ("Roomba","Smart Home",300,15);
